### ISSUE TITLE
When slider is open, color is only Teal

### ISSUE THREAD

**Issue by BirdSamuel** [suesitran/slider_side_menu#5]
https://github.com/suesitran/slider_side_menu/blob/9fd936a9188d9fdfe158e06542341cb683512655/lib/slider_side_menu.dart#L140-L142

I believe all other parts are color-customizable, however this will not allow colors to be changed when opened.
Fixing L141 (I believe to _parentEndColor?) would be a nice change to make any color be possible.

**Comment by suesitran** [comment]
good idea, but _parentEndColor is used for the icon background when menu is expanded. Maybe another color for this background color will be good.

**Comment by BirdSamuel** [comment]
> good idea, but _parentEndColor is used for the icon background when menu is expanded. Maybe another color for this background color will be good.

Agreed, even a `_parentOpenColor` set to `_parentStartColor` by default gives it some theming flexibility :-)

EDIT: Just saw the `menu-color-is-always-teal` branch, looks good to me for merging 👍🏻
